version: "3.8"

services:
  react_app_dev:
    build:
      context: .
    image: barath2707/dev
    ports:
      - "8081:80"
    networks:
      - monitoring-net

networks:
  monitoring-net:
    external: true
