version: "3.8"

services:
  react_app_prod:
    build:
      context: .
    image: barath2707/prod
    ports:
      - "8082:80"
    networks:
      - monitoring-net

networks:
  monitoring-net:
    external: true
